# Generated by Django 4.2.3 on 2023-07-17 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_service_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceitem',
            name='item_info',
            field=models.TextField(),
        ),
    ]
