# Generated by Django 4.2.3 on 2023-07-17 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_alter_serviceitem_item_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceitem',
            name='item_info',
            field=models.CharField(max_length=255),
        ),
    ]
