# Generated by Django 4.2.3 on 2023-07-25 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_service_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='info_de',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='info_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='info_uk',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='name_de',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='name_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='name_uk',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='serviceitem',
            name='item_info_de',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='serviceitem',
            name='item_info_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='serviceitem',
            name='item_info_uk',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
