# Generated by Django 4.2.3 on 2023-07-18 11:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_name', models.CharField(max_length=255)),
                ('owner_social', models.URLField(blank=True, null=True)),
                ('owner_image', models.ImageField(blank=True, upload_to='user_photo')),
                ('owner_review', models.TextField(validators=[django.core.validators.MinLengthValidator(30)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
