# Generated by Django 4.2.3 on 2023-07-22 13:02

from django.db import migrations, models



class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_remove_photo_photo_name_alter_photo_image'),
    ]

    operations = [

    ]
