# Generated by Django 4.2.3 on 2023-07-23 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_alter_category_main_image_alter_photo_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='main_image',
            field=models.ImageField(upload_to='category_images'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(upload_to='portfolio media'),
        ),
    ]
